production:
  adapter: redis
  channel_prefix: prod
  url: <%= ENV["REDIS_URL"] %>

local: &local
  adapter: redis
  channel_prefix: local
  url: <%= ENV["REDIS_URL"] %>

development: *local
test: *local
